Repository ament/ament_lint, pull requests merged in 2019-09, with the labels that each got.

#188 fix handling mixed relative/absolute path in ament_cppcheck
  ament_cppcheck/ament_cppcheck/main.py
Labels: bug, in review

#189 Install manifest file in ament_flake8
  ament_flake8/setup.py
Labels: bug, in review

#190 [backport-dashing] Install manifest file in ament_flake8
  ament_flake8/setup.py
Labels: bug, in review

#191 Add pytest marker for mypy
  ament_mypy/ament_mypy/pytest_marker.py
  ament_mypy/setup.py
Labels: enhancement

#193 install resource marker file for packages
  ament_clang_format/resource/ament_clang_format
  ament_clang_format/setup.py
  ament_clang_tidy/resource/ament_clang_tidy
  ament_clang_tidy/setup.py
  ament_copyright/resource/ament_copyright
  ament_copyright/setup.py
  ament_cppcheck/resource/ament_cppcheck
  ament_cppcheck/setup.py
  ament_cpplint/resource/ament_cpplint
  ament_cpplint/setup.py
  ament_flake8/resource/ament_flake8
  ament_flake8/setup.py
  ament_lint/resource/ament_lint
  ament_lint/setup.py
  ament_lint_cmake/resource/ament_lint_cmake
  ament_lint_cmake/setup.py
  ament_mypy/resource/ament_mypy
  ament_mypy/setup.py
  ament_pclint/resource/ament_pclint
  ament_pclint/setup.py
  ament_pep257/resource/ament_pep257
  ament_pep257/setup.py
  ament_pep8/resource/ament_pep8
  ament_pep8/setup.py
  ament_pyflakes/resource/ament_pyflakes
  ament_pyflakes/setup.py
  ament_uncrustify/resource/ament_uncrustify
  ament_uncrustify/setup.py
  ament_xmllint/resource/ament_xmllint
  ament_xmllint/setup.py
Labels: in review

#194 fix pytest warning about unknown markers
  ament_pyflakes/pytest.ini
Labels: bug, enhancement, in review
