Repository ament/ament_lint, pull requests merged in 2019-08, with the labels that each got.

#170 [dashing backport] avoid cppcheck version 1.88 due to performance issues (#168)
  ament_cmake_cppcheck/cmake/ament_cppcheck.cmake
  ament_cppcheck/ament_cppcheck/main.py
Labels: in review

#176 Ability to exclude folders with ament_pep257
  ament_pep257/ament_pep257/main.py
Labels: enhancement

#178 re-add path insertion removed from wrong package
  ament_flake8/test/test_flake8.py
Labels: bug

#181 fix cmake plugin to use correct config file argument keyword
  ament_cmake_mypy/cmake/ament_mypy.cmake
Labels: bug

#182 add config ini to ament_mypy site package
  ament_mypy/setup.py
Labels: bug

#185 install manifest files in Python packages
  ament_clang_format/setup.py
  ament_clang_tidy/setup.py
  ament_copyright/setup.py
  ament_cppcheck/setup.py
  ament_cpplint/setup.py
  ament_lint/setup.py
  ament_lint_cmake/setup.py
  ament_mypy/setup.py
  ament_pclint/setup.py
  ament_pep257/setup.py
  ament_pep8/setup.py
  ament_pyflakes/setup.py
  ament_uncrustify/setup.py
  ament_xmllint/setup.py
Labels: bug, in review

#186 [backport-dashing] install manifest files in Python packages (#185)
  ament_clang_format/setup.py
  ament_clang_tidy/setup.py
  ament_copyright/setup.py
  ament_cppcheck/setup.py
  ament_cpplint/setup.py
  ament_lint/setup.py
  ament_lint_cmake/setup.py
  ament_pclint/setup.py
  ament_pep257/setup.py
  ament_pep8/setup.py
  ament_pyflakes/setup.py
  ament_uncrustify/setup.py
  ament_xmllint/setup.py
Labels: bug, in review
