Repository ament/ament_lint, pull requests merged in 2019-07, with the labels that each got.

#153 Add custom config file support for clang-format
  ament_cmake_clang_format/cmake/ament_clang_format.cmake
Labels: enhancement

#159 Add custom config file support for clang-tidy
  ament_cmake_clang_tidy/cmake/ament_clang_tidy.cmake
Labels: enhancement

#160 Match copyright templates with differing whitespace
  ament_copyright/ament_copyright/parser.py
  ament_copyright/test/cases/bsd_license/case.py
  ament_copyright/test/cases/bsd_license_indented/case.py
  ament_copyright/test/cases/bsd_license_tabs/case.py
  ament_copyright/test/test_copyright.py
Labels: enhancement, in review

#168 avoid cppcheck version 1.88 due to performance issues
  ament_cmake_cppcheck/cmake/ament_cppcheck.cmake
  ament_cppcheck/ament_cppcheck/main.py
Labels: in review
