Repository ament/ament_lint, pull requests merged in 2019-03, with the labels that each got.

#128 fix name of included CMake file for cmake_clang_format
  ament_cmake_clang_format/ament_cmake_clang_format-extras.cmake
  ament_cmake_clang_format/cmake/ament_clang_format.cmake
Labels: bug, in review

#130 [Crystal] Remove make_notifier() call
  ament_flake8/ament_flake8/main.py
Labels: in review

#131 [Crystal] use --extend-ignore for flake8 to keep default ignores
  ament_flake8/ament_flake8/configuration/ament_flake8.ini
Labels: in progress

#134 fix cppcheck report to list checked files
  ament_cppcheck/ament_cppcheck/main.py
Labels: bug, in review

#135 use yaml.safe_load instead of deprecated yaml.load
  ament_clang_format/ament_clang_format/main.py
Labels: in review

#126 Adding GPL (and LGPL)
  ament_copyright/ament_copyright/licenses.py
  ament_copyright/ament_copyright/template/gplv3_contributing.txt
  ament_copyright/ament_copyright/template/gplv3_header.txt
  ament_copyright/ament_copyright/template/gplv3_license.txt
  ament_copyright/ament_copyright/template/lgplv3_contributing.txt
  ament_copyright/ament_copyright/template/lgplv3_header.txt
  ament_copyright/ament_copyright/template/lgplv3_license.txt
  ament_copyright/setup.py
Labels: in review
