Repository ament/ament_lint, pull requests merged in 2020-05, with the labels that each got.

#242 support flake8 3.8 while maintaining compatibility with older versions
  ament_flake8/ament_flake8/main.py
Labels: bug

#234 Updated cpplint and cppcheck to exclude directories and files
  ament_cmake_cppcheck/cmake/ament_cmake_cppcheck_lint_hook.cmake
  ament_cmake_cppcheck/cmake/ament_cppcheck.cmake
  ament_cmake_cpplint/cmake/ament_cmake_cpplint_lint_hook.cmake
  ament_cmake_cpplint/cmake/ament_cpplint.cmake
  ament_cmake_uncrustify/cmake/ament_cmake_uncrustify_lint_hook.cmake
  ament_cppcheck/ament_cppcheck/main.py
Labels: enhancement

#249 Close source files after reading them
  ament_cpplint/ament_cpplint/cpplint.py
  ament_lint_cmake/ament_lint_cmake/cmakelint.py
Labels: bug, in review

#239 Allow to configure language in cppcheck with a global var
  ament_cmake_cppcheck/cmake/ament_cmake_cppcheck_lint_hook.cmake
Labels: enhancement
