Repository ament/ament_lint, pull requests merged in 2021-01, with the labels that each got.

#290 Support Python 3.8-provided importlib.metadata
  ament_copyright/ament_copyright/__init__.py
Labels: bug

#291 Drop trailing tab from package manifests
  ament_clang_format/package.xml
  ament_cmake_clang_format/package.xml
  ament_cmake_copyright/package.xml
  ament_cmake_cppcheck/package.xml
  ament_cmake_cpplint/package.xml
  ament_cmake_lint_cmake/package.xml
  ament_cmake_pclint/package.xml
  ament_cmake_pep257/package.xml
  ament_cmake_pycodestyle/package.xml
  ament_cmake_pyflakes/package.xml
  ament_cmake_uncrustify/package.xml
  ament_cmake_xmllint/package.xml
  ament_copyright/package.xml
  ament_cppcheck/package.xml
  ament_cpplint/package.xml
  ament_lint/package.xml
  ament_lint_auto/package.xml
  ament_lint_cmake/package.xml
  ament_lint_common/package.xml
  ament_pclint/package.xml
  ament_pep257/package.xml
  ament_pycodestyle/package.xml
  ament_pyflakes/package.xml
  ament_uncrustify/package.xml
  ament_xmllint/package.xml
Labels: in review

#202 Add pytest marks to ament_pclint tests.
  ament_pclint/test/test_copyright.py
  ament_pclint/test/test_flake8.py
  ament_pclint/test/test_pep257.py
Labels: in review

#235 Make CMake linter line length configurable
  ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake
  ament_lint_cmake/ament_lint_cmake/cmakelint.py
  ament_lint_cmake/ament_lint_cmake/main.py
Labels: enhancement
